<?php
class Bf_Util {
	public static function jsonStrToAssociativeArray($jsonStr) {
		return json_decode($jsonStr, true);
	}

	/**
     * @author devilan (REMOVEIT) (at) o2 (dot) pl
     * For PHP5.3 users who want to emulate JSON_UNESCAPED_UNICODE
     * @see https://php.net/manual/en/function.json-encode.php#105789
     */
	public static function associativeArrayToJsonStr($arr, $optionsBitMask = 0) {
		if(defined('JSON_UNESCAPED_UNICODE')) {
			return json_encode($arr, JSON_UNESCAPED_UNICODE | $optionsBitMask);
		}

		$convmap = array(0x80, 0xffff, 0, 0xffff);

        //convmap since 0x80 char codes so it takes all multibyte codes (above ASCII 127). So such characters are being "hidden" from normal json_encoding
        array_walk_recursive($arr, function (&$item, $key) use(&$convmap) {
            if (is_string($item)) {
                $item = mb_encode_numericentity($item, $convmap, 'UTF-8');
            }
        });
        return mb_decode_numericentity(json_encode($arr, $optionsBitMask), $convmap, 'UTF-8');
	}

	/**
     * Returns date formatted as BillForward's UTC ISO8601 string.
     * @param int The timestamp (for example generated by time())
     * @return string The BillForward-formatted time. (Example: '2015-04-23T17:13:37Z')
     */
    public static function makeBillForwardDate($time) {
    	// convert to UTC ISO8601 date
		$isoFormatted = gmdate(DATE_ISO8601, $time);
		// replace "+0000 with Z"
		$formattedTimezone = substr($isoFormatted, 0, strlen($isoFormatted)-5).'Z';

		return $formattedTimezone;
    }

    /**
     * Returns PHP time integer from BillForward's UTC ISO8601 string.
     * @param string The BillForward-formatted time (Example: '2015-04-23T17:13:37Z')
     * @return int The timestamp
     */
    public static function makeUTCTimeFromBillForwardDate($date) {
    	$dateTime = new DateTime($date, new DateTimeZone('UTC'));
    	return $dateTime->getTimestamp();
    }
}